/**
 * This file generated by Apso.
 */
import { CourseModule } from './Course/Course.module';
import { StudentModule } from './Student/Student.module';
import { InstructorModule } from './Instructor/Instructor.module';
import { AssignmentModule } from './Assignment/Assignment.module';
import { EnrollmentModule } from './Enrollment/Enrollment.module';

export default [
  CourseModule,
  StudentModule,
  InstructorModule,
  AssignmentModule,
  EnrollmentModule,
];
